# Generated by Django 5.0.2 on 2024-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER')], default='user', max_length=50)),
            ],
        ),
    ]
